baseurl = "http://isubuz.github.io/"
languageCode = "en-us"
title = "iSubuz"

[params]
Author = "Subhajit Ghosh"
Tagline = "Lead @Skipjaq"
AuthorEmail = "i.subhajit.ghosh@gmail.com"
FeedBurner = ""
DateForm = "Jan 2, 2006"
